version: '3.9'

services:
  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: socialapp
    volumes:
      - .:/socialapp
    ports:
      - "8000:8000"
