# Generated by Django 5.1 on 2024-08-26 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_app", "0003_customuser_groups_customuser_user_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="friends",
            field=models.JSONField(default=[]),
        ),
    ]
